#include "ui_opencode.h"
#include <lvgl.h>
#include <string.h>
#include "oc_logo.h"
#include "hal/board_caps.h"

// IBM Plex Mono (SIL OFL 1.1), generated by WP1
LV_FONT_DECLARE(font_plex_48);
LV_FONT_DECLARE(font_plex_40);
LV_FONT_DECLARE(font_plex_24);
LV_FONT_DECLARE(font_plex_18);
LV_FONT_DECLARE(font_plex_16);
LV_FONT_DECLARE(font_plex_12);

// Tokens de diseño de OpenCode (SPEC.md §3). Son locales a este archivo a
// propósito: las pantallas de Claude guardan la paleta en theme.h y no deben
// cambiar.
#define OC_ELEMENT   lv_color_hex(0x1e1e1e)   // relleno de la barra y de los chips
#define OC_BORDER    lv_color_hex(0x3c3c3c)   // contorno de 1 px de los paneles
#define OC_TEXT      lv_color_hex(0xeeeeee)
#define OC_MUTED     lv_color_hex(0x808080)   // etiquetas y líneas secundarias
#define OC_PRIMARY   lv_color_hex(0xfab283)   // melocotón de marca: barras y chips
#define OC_ERROR     lv_color_hex(0xe06c75)   // >= 85 %, limitado, sin datos, enlace caído
#define OC_SUCCESS   lv_color_hex(0x7fd88f)   // cuadrado de sesión activa

// Glifos, siempre escritos con sus espacios alrededor en el punto de uso:
// " · " y "o " forman parte del texto, no son decoración.
#define OC_MIDDOT    "\xC2\xB7"              // ·
#define OC_ELLIPSIS  "\xE2\x80\xA6"          // …
// U+25CB (○) no está en IBM Plex Mono, tampoco tras regenerar los fonts: los
// fonts generados cubren 0x20-0x7E, los acentos del español (á é í ó ú ü ñ
// ¡ ¿) y U+00B7 y U+2026, pero no ese glifo. Por eso las líneas de estado
// "desactualizado" y "sin conexión" usan una "o" sencilla (SPEC.md §7,
// IMPL.md WP1).
#define OC_CIRCLE    "o"

#define OC_FRESH_MS  300000u     // un payload más antiguo que esto está desactualizado
#define OC_BLINK_MS  500u        // parpadeo de 1 Hz en el cuadrado de sesión activa
#define OC_SEG_MAX   34          // máximo de segmentos de cualquier diseño (corte de 480)
#define OC_PANELS    2

// Geometría de la pantalla, elegida una vez según la placa activa. Los valores
// en píxeles vienen del anexo A de SPEC.md; son los mismos tres cortes que usa
// ui.cpp.
struct OcLayout {
    int16_t scr_w, scr_h;

    int16_t mark_x, mark_y;
    int16_t wordmark_x, wordmark_y;

    int16_t panel_x, panel_w, panel_h;
    int16_t panel1_y, panel2_y;
    int16_t pad_x;
    int16_t hero_top;
    int16_t chip_top, chip_h, chip_px;
    int16_t bar_top, bar_segs, bar_seg_w, bar_seg_h, bar_gap;
    int16_t reset_top;

    bool    has_stats;
    int16_t stats_title_y, stats_val_y;
    int16_t stats_x[3];
    int16_t stats_trunc;

    int16_t status_y, status_sq, status_text_x;

    const lv_font_t *hero_font;
    const lv_font_t *chip_font;
    const lv_font_t *line_font;    // línea de reinicio / coste + línea de estado
    const lv_font_t *stats_font;
    const lv_image_dsc_t *mark_dsc;
    const lv_image_dsc_t *wordmark_dsc;
};
static OcLayout L = {};

static void compute_layout(const BoardCaps &c) {
    L.scr_w = c.width;
    L.scr_h = c.height;

    if (c.height >= 460) {
        // Grande — ajustado para 480x480 (AMOLED-2.16).
        L.mark_x = 20; L.mark_y = 24;
        L.wordmark_y = 32;
        L.mark_dsc = &oc_mark_l;
        L.wordmark_dsc = &oc_wordmark_l;
        L.panel_x = 20; L.panel_h = 132; L.panel1_y = 96; L.panel2_y = 240;
        L.pad_x = 16;
        L.hero_top = 12;
        L.chip_top = 18; L.chip_h = 26; L.chip_px = 8;
        L.bar_top = 72; L.bar_segs = 34; L.bar_seg_w = 10; L.bar_seg_h = 20; L.bar_gap = 2;
        L.reset_top = 104;
        L.has_stats = true;
        L.stats_title_y = 386; L.stats_val_y = 410;
        L.stats_x[0] = 20; L.stats_x[1] = 150; L.stats_x[2] = 370;
        L.stats_trunc = 12;
        L.status_y = 448; L.status_sq = 10; L.status_text_x = 38;
        L.hero_font = &font_plex_48;
        L.chip_font = &font_plex_18;
        L.line_font = &font_plex_18;
        L.stats_font = &font_plex_18;
    } else if (c.height >= 300) {
        // Compacto — ajustado para 368x448 (AMOLED-1.8).
        L.mark_x = 20; L.mark_y = 22;
        L.wordmark_y = 30;
        L.mark_dsc = &oc_mark_m;
        L.wordmark_dsc = &oc_wordmark_m;
        L.panel_x = 20; L.panel_h = 116; L.panel1_y = 80; L.panel2_y = 206;
        L.pad_x = 14;
        L.hero_top = 10;
        L.chip_top = 14; L.chip_h = 22; L.chip_px = 6;
        L.bar_top = 60; L.bar_segs = 25; L.bar_seg_w = 10; L.bar_seg_h = 16; L.bar_gap = 2;
        L.reset_top = 92;
        L.has_stats = true;
        L.stats_title_y = 334; L.stats_val_y = 356;
        L.stats_x[0] = 20; L.stats_x[1] = 120; L.stats_x[2] = 276;
        L.stats_trunc = 9;
        L.status_y = 404; L.status_sq = 8; L.status_text_x = 34;
        L.hero_font = &font_plex_40;
        L.chip_font = &font_plex_16;
        L.line_font = &font_plex_16;
        L.stats_font = &font_plex_16;
    } else {
        // Pequeño — ajustado para 240x240 (LCD-1.54): sin bloque de estadísticas.
        L.mark_x = 8; L.mark_y = 6;
        L.wordmark_y = 10;
        L.mark_dsc = &oc_mark_s;
        L.wordmark_dsc = &oc_wordmark_s;
        L.panel_x = 8; L.panel_h = 82; L.panel1_y = 34; L.panel2_y = 122;
        L.pad_x = 8;
        L.hero_top = 6;
        L.chip_top = 8; L.chip_h = 16; L.chip_px = 5;
        L.bar_top = 38; L.bar_segs = 18; L.bar_seg_w = 9; L.bar_seg_h = 10; L.bar_gap = 2;
        L.reset_top = 58;
        L.has_stats = false;
        L.status_y = 214; L.status_sq = 6; L.status_text_x = 18;
        L.hero_font = &font_plex_24;
        L.chip_font = &font_plex_12;
        L.line_font = &font_plex_12;
        L.stats_font = &font_plex_12;
    }

    // Los paneles ocupan la pantalla menos los dos márgenes, y el wordmark se
    // centra sea cual sea el ancho de la placa (las imágenes generadas son de
    // 195/156/117 px).
    L.panel_w = L.scr_w - 2 * L.panel_x;
    L.wordmark_x = (L.scr_w - L.wordmark_dsc->header.w) / 2;

    // Las placas que caen en el corte grande con un panel más estrecho que
    // 480 px (p. ej. la AMOLED-2.06 de 410x502) mantienen el número de
    // segmentos y dejan que los bloques se encojan en lugar de salirse del
    // panel.
    int16_t avail = L.panel_w - 2 * L.pad_x;
    int16_t fits = (avail - (L.bar_segs - 1) * L.bar_gap) / L.bar_segs;
    if (fits > 0 && L.bar_seg_w > fits) L.bar_seg_w = fits;
}

// ---- Controles ----
static lv_obj_t *root;                                    // el contenedor de la pantalla
static lv_obj_t *dim_group;                               // paneles + estadísticas: se atenúan al desactualizarse
static lv_obj_t *panel[OC_PANELS];
static lv_obj_t *hero[OC_PANELS];
static lv_obj_t *chip[OC_PANELS];
static lv_obj_t *seg[OC_PANELS][OC_SEG_MAX];
static lv_obj_t *reset_lbl[OC_PANELS];
static lv_obj_t *stats_title[3];
static lv_obj_t *stats_val[3];
static lv_obj_t *status_sq;                               // cuadrado parpadeante de "sesión activa"
static lv_obj_t *status_lbl;

// ---- Estado ----
static OcData   cur;                 // último payload, copiado por valor
static bool     have_data = false;   // llegó un payload válido desde el arranque
static uint32_t data_ms = 0;         // millis() de ese payload
static bool     ble_on = false;
static bool     dimmed = false;      // opacidad actual de dim_group
static bool     bar_vis[OC_PANELS] = { false, false };
static bool     sq_shown = false;    // cuadrado visible actualmente
static bool     blink_on = true;
static uint32_t blink_ms = 0;
static char     status_text[64] = "";
// Ambos empiezan "sin definir" (el negro nunca es un color de estado y -1 es
// "sin x") para que el primer dibujo siempre los envíe; después solo los
// cambios reales llegan a LVGL.
static lv_color_t status_color;
static int16_t  status_x = -1;

static void draw_status(uint32_t now);
static void apply_dim(bool stale);
static void redraw(void);

// ---- Formato (refleja los ayudantes del prototipo) ----

// "42 min" / "2 h 14 min" / "6 d 13 h"; una cuenta atrás desconocida muestra
// los puntos suspensivos.
static const char *fmt_mins(int mins) {
    static char buf[16];
    if (mins < 0) return OC_ELLIPSIS;
    if (mins >= 1440)      snprintf(buf, sizeof(buf), "%d d %d h", mins / 1440, (mins % 1440) / 60);
    else if (mins >= 60)   snprintf(buf, sizeof(buf), "%d h %d min", mins / 60, mins % 60);
    else                   snprintf(buf, sizeof(buf), "%d min", mins);
    return buf;
}

// "35 s" / "21 min" / "3 h 4 min" — el sufijo "hace …" de la línea de estado.
static const char *fmt_age(long secs) {
    static char buf[16];
    if (secs < 0) secs = 0;
    if (secs < 60)        snprintf(buf, sizeof(buf), "%ld s", secs);
    else if (secs < 3600) snprintf(buf, sizeof(buf), "%ld min", secs / 60);
    else                  snprintf(buf, sizeof(buf), "%ld h %ld min", secs / 3600, (secs % 3600) / 60);
    return buf;
}

// Los tokens llegan en miles: 812 -> "812k", 3200 -> "3.2M", 106969 -> "107.0M".
static const char *fmt_tokens(long thousands) {
    static char buf[12];
    if (thousands < 0) thousands = 0;
    if (thousands < 1000)        snprintf(buf, sizeof(buf), "%ldk", thousands);
    else if (thousands < 1000000) snprintf(buf, sizeof(buf), "%.1fM", thousands / 1000.0f);
    else                          snprintf(buf, sizeof(buf), "%.1fB", thousands / 1000000.0f);
    return buf;
}

// "ds-v4.1-flash" -> "ds-v4.1-fl…" para que las columnas nunca choquen (anexo A).
static void fmt_model(char *out, size_t len) {
    if ((int)strlen(cur.m) > L.stats_trunc)
        snprintf(out, len, "%.*s" OC_ELLIPSIS, L.stats_trunc, cur.m);
    else
        snprintf(out, len, "%s", cur.m);
}

static bool is_stale(uint32_t now) {
    return have_data && (now - data_ms) > OC_FRESH_MS;
}

// ---- Constructores ----

// Grupo transparente, sin borde y permeable al tacto. EVENT_BUBBLE en cada
// control para que un toque en cualquier parte llegue a la raíz de la pantalla,
// donde escucha ui.cpp.
static lv_obj_t *make_group(lv_obj_t *parent) {
    lv_obj_t *g = lv_obj_create(parent);
    lv_obj_set_size(g, L.scr_w, L.scr_h);
    lv_obj_set_pos(g, 0, 0);
    lv_obj_set_style_bg_opa(g, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(g, 0, 0);
    lv_obj_set_style_pad_all(g, 0, 0);
    lv_obj_clear_flag(g, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(g, LV_OBJ_FLAG_EVENT_BUBBLE);
    return g;
}

// Contorno fino de esquinas cuadradas; los hijos se posicionan a mano.
static lv_obj_t *make_panel(lv_obj_t *parent, int16_t y) {
    lv_obj_t *p = lv_obj_create(parent);
    lv_obj_set_pos(p, L.panel_x, y);
    lv_obj_set_size(p, L.panel_w, L.panel_h);
    lv_obj_set_style_bg_opa(p, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_color(p, OC_BORDER, 0);
    lv_obj_set_style_border_width(p, 1, 0);
    lv_obj_set_style_radius(p, 0, 0);
    lv_obj_set_style_pad_all(p, 0, 0);
    lv_obj_clear_flag(p, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(p, LV_OBJ_FLAG_EVENT_BUBBLE);
    return p;
}

static lv_obj_t *make_label(lv_obj_t *parent, int16_t x, int16_t y,
                            const lv_font_t *font, lv_color_t color) {
    lv_obj_t *l = lv_label_create(parent);
    lv_obj_set_pos(l, x, y);
    lv_obj_set_style_text_font(l, font, 0);
    lv_obj_set_style_text_color(l, color, 0);
    lv_obj_set_style_pad_all(l, 0, 0);
    // Una sola línea, como el white-space: nowrap del prototipo.
    lv_label_set_long_mode(l, LV_LABEL_LONG_MODE_CLIP);
    lv_obj_add_flag(l, LV_OBJ_FLAG_EVENT_BUBBLE);
    return l;
}

// Chip estilo terminal: relleno plano, relleno horizontal, altura fija y
// anclado al padding derecho del panel.
static lv_obj_t *make_chip(lv_obj_t *parent, int16_t y) {
    lv_obj_t *c = make_label(parent, 0, y, L.chip_font, OC_PRIMARY);
    int16_t text_h = lv_font_get_line_height(L.chip_font);
    lv_obj_set_style_bg_color(c, OC_ELEMENT, 0);
    lv_obj_set_style_bg_opa(c, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(c, 0, 0);
    lv_obj_set_style_pad_left(c, L.chip_px, 0);
    lv_obj_set_style_pad_right(c, L.chip_px, 0);
    lv_obj_set_style_pad_top(c, (L.chip_h - text_h) / 2, 0);
    lv_obj_set_style_pad_bottom(c, L.chip_h - text_h - (L.chip_h - text_h) / 2, 0);
    lv_obj_set_height(c, L.chip_h);
    // El ancho sigue al texto, así que LVGL recalcula la alineación a la
    // derecha cada vez que cambia el texto de la etiqueta.
    lv_obj_align(c, LV_ALIGN_TOP_RIGHT, -L.pad_x, y);
    return c;
}

static lv_obj_t *make_seg(lv_obj_t *parent, int16_t x, int16_t y) {
    lv_obj_t *s = lv_obj_create(parent);
    lv_obj_set_pos(s, x, y);
    lv_obj_set_size(s, L.bar_seg_w, L.bar_seg_h);
    lv_obj_set_style_bg_color(s, OC_ELEMENT, 0);
    lv_obj_set_style_bg_opa(s, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(s, 0, 0);
    lv_obj_set_style_radius(s, 0, 0);
    lv_obj_set_style_pad_all(s, 0, 0);
    lv_obj_clear_flag(s, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s, LV_OBJ_FLAG_EVENT_BUBBLE);
    return s;
}

static void build_panel(int i, int16_t y) {
    panel[i] = make_panel(dim_group, y);
    hero[i] = make_label(panel[i], L.pad_x, L.hero_top, L.hero_font, OC_TEXT);
    chip[i] = make_chip(panel[i], L.chip_top);
    for (int k = 0; k < L.bar_segs; k++)
        seg[i][k] = make_seg(panel[i], L.pad_x + k * (L.bar_seg_w + L.bar_gap), L.bar_top);
    reset_lbl[i] = make_label(panel[i], L.pad_x, L.reset_top, L.line_font, OC_MUTED);
}

void oc_usage_init(lv_obj_t *parent) {
    compute_layout(board_caps());

    root = make_group(parent);
    // La marca y el wordmark se quedan a opacidad completa aunque las cifras de
    // abajo se atenúen. El widget de batería es de ui.cpp y se mantiene encima.
    lv_obj_t *mark = lv_image_create(root);
    lv_image_set_src(mark, L.mark_dsc);
    lv_obj_set_pos(mark, L.mark_x, L.mark_y);
    lv_obj_add_flag(mark, LV_OBJ_FLAG_EVENT_BUBBLE);

    lv_obj_t *wordmark = lv_image_create(root);
    lv_image_set_src(wordmark, L.wordmark_dsc);
    lv_obj_set_pos(wordmark, L.wordmark_x, L.wordmark_y);
    lv_obj_add_flag(wordmark, LV_OBJ_FLAG_EVENT_BUBBLE);

    dim_group = make_group(root);
    build_panel(0, L.panel1_y);
    build_panel(1, L.panel2_y);

    if (L.has_stats) {
        for (int i = 0; i < 3; i++) {
            stats_title[i] = make_label(dim_group, L.stats_x[i], L.stats_title_y, L.stats_font, OC_TEXT);
            stats_val[i] = make_label(dim_group, L.stats_x[i], L.stats_val_y, L.stats_font, OC_MUTED);
        }
    }

    // Línea de estado (fuera de dim_group). El cuadrado va en el margen de la
    // pantalla y se centra en la línea de texto; la x del texto está en
    // draw_status().
    status_sq = lv_obj_create(root);
    lv_obj_set_pos(status_sq, L.panel_x,
                   L.status_y + (lv_font_get_line_height(L.line_font) - L.status_sq) / 2);
    lv_obj_set_size(status_sq, L.status_sq, L.status_sq);
    lv_obj_set_style_bg_color(status_sq, OC_SUCCESS, 0);
    lv_obj_set_style_bg_opa(status_sq, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(status_sq, 0, 0);
    lv_obj_set_style_radius(status_sq, 0, 0);
    lv_obj_set_style_pad_all(status_sq, 0, 0);
    lv_obj_clear_flag(status_sq, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(status_sq, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_add_flag(status_sq, LV_OBJ_FLAG_HIDDEN);

    status_lbl = make_label(root, L.panel_x, L.status_y, L.line_font, OC_MUTED);
    lv_label_set_text(status_lbl, "");

    // Estado neutro, para que la pantalla nunca quede vacía si se muestra antes
    // del primer payload (ui.cpp mantiene las pantallas OC fuera del ciclo
    // hasta entonces).
    memset(&cur, 0, sizeof(cur));
    strlcpy(cur.src, "api", sizeof(cur.src));
    cur.r5 = cur.rw = -1;
    redraw();

    lv_obj_add_flag(root, LV_OBJ_FLAG_HIDDEN);
}

// ---- Dibujo ----

static void set_bar_visible(int i, bool on) {
    if (bar_vis[i] == on) return;
    bar_vis[i] = on;
    for (int k = 0; k < L.bar_segs; k++) {
        if (on) lv_obj_clear_flag(seg[i][k], LV_OBJ_FLAG_HIDDEN);
        else     lv_obj_add_flag(seg[i][k], LV_OBJ_FLAG_HIDDEN);
    }
}

static void draw_bar(int i, int pct) {
    bool hot = (pct >= 85 || cur.limited);
    lv_color_t fill = hot ? OC_ERROR : OC_PRIMARY;
    int filled = (pct * L.bar_segs + 50) / 100;   // round(pct/100 * segs)
    if (filled < 0) filled = 0;
    if (filled > L.bar_segs) filled = L.bar_segs;
    for (int k = 0; k < L.bar_segs; k++)
        lv_obj_set_style_bg_color(seg[i][k], k < filled ? fill : OC_ELEMENT, 0);
}

static void draw_panels(bool solo) {
    const int pct[OC_PANELS] = { cur.p5, cur.pw };
    const int rst[OC_PANELS] = { cur.r5, cur.rw };
    const long tok[OC_PANELS] = { cur.tk, cur.t7 };
    const float money[OC_PANELS] = { cur.cd, cur.c7 };

    for (int i = 0; i < OC_PANELS; i++) {
        if (solo) lv_label_set_text(hero[i], fmt_tokens(tok[i]));
        else       lv_label_set_text_fmt(hero[i], "%d%%", pct[i]);

        // El modo de solo consumo cambia el chip de ventana por lo que muestra el héroe.
        char cbuf[24];
        if (solo) {
            snprintf(cbuf, sizeof(cbuf), "%s", i == 0 ? "hoy" : "7 días");
        } else if (cur.limited && pct[i] >= 100) {
            snprintf(cbuf, sizeof(cbuf), "límite");
        } else if (strcmp(cur.src, "est") == 0) {
            snprintf(cbuf, sizeof(cbuf), "%s " OC_MIDDOT " est.", i == 0 ? "5 h" : "semana");
        } else {
            snprintf(cbuf, sizeof(cbuf), "%s", i == 0 ? "5 h" : "semana");
        }
        lv_label_set_text(chip[i], cbuf);
        lv_obj_set_style_text_color(chip[i],
                                    (pct[i] >= 85 || cur.limited) ? OC_ERROR : OC_PRIMARY, 0);

        set_bar_visible(i, !solo);
        if (!solo) draw_bar(i, pct[i]);

        // El dinero pasa por snprintf: lv_label_set_text_fmt() ejecuta el printf
        // propio de LVGL, que no admite decimales (LV_USE_FLOAT está apagado).
        char mbuf[24];
        if (solo) {
            snprintf(mbuf, sizeof(mbuf), "$%.2f gastado", money[i]);
            lv_label_set_text(reset_lbl[i], mbuf);
        } else if (i == 0 && cur.r5 == -1) {
            lv_label_set_text(reset_lbl[i], "Sin ventana activa");
        } else {
            lv_label_set_text_fmt(reset_lbl[i], "Se renueva en %s", fmt_mins(rst[i]));
        }
    }
}

static void draw_stats(bool solo) {
    if (!L.has_stats) return;

    char model[20];
    char val[24];
    fmt_model(model, sizeof(model));

    lv_label_set_text(stats_title[0], "Tokens 7 d");
    lv_label_set_text(stats_title[1], "Modelo principal");
    lv_label_set_text(stats_title[2], solo ? "Gasto 7 d" : "mes");

    lv_label_set_text(stats_val[0], fmt_tokens(cur.t7));
    snprintf(val, sizeof(val), "%s %d%%", model, cur.ms);
    lv_label_set_text(stats_val[1], val);
    if (solo) {
        snprintf(val, sizeof(val), "$%.2f", cur.c7);
    } else {
        // Porcentaje del mes + días completos que quedan del periodo de facturación.
        snprintf(val, sizeof(val), "%d%% " OC_MIDDOT " %d d", cur.pm, (cur.rm + 720) / 1440);
    }
    lv_label_set_text(stats_val[2], val);
}

// SPEC.md §7. La línea vive fuera de dim_group: es así como el usuario se
// entera de que las cifras de arriba están desactualizadas o de que el enlace
// cayó. oc_usage_tick() la ejecuta en cada vuelta del bucle, así que solo lo
// que realmente cambió se envía a LVGL.
static void draw_status(uint32_t now) {
    char buf[64];
    const char *text;
    lv_color_t color;
    bool dot;

    if (!ble_on) {
        text = OC_CIRCLE " Bluetooth desconectado";
        color = OC_ERROR;
        dot = false;
    } else if (is_stale(now)) {
        snprintf(buf, sizeof(buf), OC_CIRCLE " desactualizado " OC_MIDDOT " hace %s",
                 fmt_age((long)((now - data_ms) / 1000)));
        text = buf;
        color = OC_ERROR;
        dot = false;
    } else if (cur.a >= 1) {
        if (cur.ag[0]) snprintf(buf, sizeof(buf), "%s " OC_MIDDOT " trabajando", cur.ag);
        else           snprintf(buf, sizeof(buf), "trabajando");
        text = buf;
        color = OC_TEXT;
        dot = true;
    } else {
        long age = cur.la + (have_data ? (long)((now - data_ms) / 1000) : 0);
        snprintf(buf, sizeof(buf), "inactivo " OC_MIDDOT " última actividad hace %s", fmt_age(age));
        text = buf;
        color = OC_MUTED;
        dot = false;
    }

    if (strcmp(text, status_text) != 0) {
        lv_label_set_text(status_lbl, text);
        strlcpy(status_text, text, sizeof(status_text));
    }
    if (!lv_color_eq(color, status_color)) {
        status_color = color;
        lv_obj_set_style_text_color(status_lbl, color, 0);
    }
    // El estado activo sangra el texto para dejar libre el cuadrado
    // parpadeante; los otros tres estados empiezan en el margen de la pantalla
    // (anexo A).
    int16_t x = dot ? L.status_text_x : L.panel_x;
    if (x != status_x) {
        status_x = x;
        lv_obj_set_pos(status_lbl, x, L.status_y);
    }

    if (dot != sq_shown) {
        sq_shown = dot;
        if (dot) {
            blink_on = true;
            blink_ms = now;
            lv_obj_set_style_bg_opa(status_sq, LV_OPA_COVER, 0);
            lv_obj_clear_flag(status_sq, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(status_sq, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

static void apply_dim(bool stale) {
    bool dim = stale || !ble_on;
    if (dim == dimmed) return;
    dimmed = dim;
    // La opacidad se hereda, así que los paneles y las estadísticas se atenúan
    // como un solo bloque mientras la cabecera y la línea de estado mantienen
    // la opacidad completa.
    lv_obj_set_style_opa(dim_group, dim ? LV_OPA_40 : LV_OPA_COVER, 0);
}

static void redraw(void) {
    if (!root) return;
    bool solo = strcmp(cur.src, "none") == 0;
    uint32_t now = millis();
    draw_panels(solo);
    draw_stats(solo);
    draw_status(now);
    apply_dim(is_stale(now));
}

// ======== API pública ========

void oc_usage_show(void) {
    if (!root) return;
    lv_obj_clear_flag(root, LV_OBJ_FLAG_HIDDEN);
    redraw();               // la cuenta atrás y el sufijo "hace" avanzaron mientras estaba oculta
}

void oc_usage_hide(void) {
    if (!root) return;
    lv_obj_add_flag(root, LV_OBJ_FLAG_HIDDEN);
}

lv_obj_t *oc_usage_get_root(void) {
    return root;
}

void oc_usage_update(const OcData *d) {
    if (!d) return;
    cur = *d;
    data_ms = millis();
    if (d->valid) have_data = true;
    redraw();
}

void oc_usage_set_ble(bool connected) {
    ble_on = connected;
    redraw();
}

void oc_usage_tick(void) {
    if (!root) return;
    uint32_t now = millis();

    // Tanto el cambio a desactualizado como los contadores "hace …" dependen
    // del tiempo, así que siguen corriendo entre los payloads de ~60 s.
    apply_dim(is_stale(now));
    draw_status(now);

    if (sq_shown && now - blink_ms >= OC_BLINK_MS) {
        blink_ms = now;
        blink_on = !blink_on;
        lv_obj_set_style_bg_opa(status_sq, blink_on ? LV_OPA_COVER : LV_OPA_30, 0);
    }
}

bool oc_has_data(void) {
    return have_data;
}
