#include "ui_opencode.h"
#include <lvgl.h>
#include <string.h>
#include "oc_logo.h"
#include "hal/board_caps.h"

// IBM Plex Mono (SIL OFL 1.1), generated by WP1
LV_FONT_DECLARE(font_plex_48);
LV_FONT_DECLARE(font_plex_40);
LV_FONT_DECLARE(font_plex_24);
LV_FONT_DECLARE(font_plex_18);
LV_FONT_DECLARE(font_plex_16);
LV_FONT_DECLARE(font_plex_12);

// OpenCode design tokens (SPEC.md §3). Local to this file on purpose: the
// Claude screens keep the palette in theme.h and must not change.
#define OC_ELEMENT   lv_color_hex(0x1e1e1e)   // bar track + chip fill
#define OC_BORDER    lv_color_hex(0x3c3c3c)   // 1 px panel outline
#define OC_TEXT      lv_color_hex(0xeeeeee)
#define OC_MUTED     lv_color_hex(0x808080)   // labels and secondary lines
#define OC_PRIMARY   lv_color_hex(0xfab283)   // brand peach: bars and chips
#define OC_ERROR     lv_color_hex(0xe06c75)   // >= 85%, limited, no data, link down
#define OC_SUCCESS   lv_color_hex(0x7fd88f)   // active-session square

// Glyphs, always written with the surrounding spaces spelled out at the call
// site: " · " and "o " are part of the text, not decoration.
#define OC_MIDDOT    "\xC2\xB7"              // ·
#define OC_ELLIPSIS  "\xE2\x80\xA6"          // …
// U+25CB (○) is not part of IBM Plex Mono — the generated fonts cover
// 0x20-0x7E plus U+00B7 and U+2026 — so the stale/offline status lines fall
// back to a plain "o" (SPEC.md §7, IMPL.md WP1).
#define OC_CIRCLE    "o"

#define OC_FRESH_MS  300000u     // payload older than this = stale
#define OC_BLINK_MS  500u        // 1 Hz blink on the active-session square
#define OC_SEG_MAX   34          // most segments of any layout (480 breakpoint)
#define OC_PANELS    2

// Screen geometry, picked once from the active board. Pixel values come from
// SPEC.md Annex A; the same three breakpoints ui.cpp uses.
struct OcLayout {
    int16_t scr_w, scr_h;

    int16_t mark_x, mark_y;
    int16_t wordmark_x, wordmark_y;

    int16_t panel_x, panel_w, panel_h;
    int16_t panel1_y, panel2_y;
    int16_t pad_x;
    int16_t hero_top;
    int16_t chip_top, chip_h, chip_px;
    int16_t bar_top, bar_segs, bar_seg_w, bar_seg_h, bar_gap;
    int16_t reset_top;

    bool    has_stats;
    int16_t stats_title_y, stats_val_y;
    int16_t stats_x[3];
    int16_t stats_trunc;

    int16_t status_y, status_sq, status_text_x;

    const lv_font_t *hero_font;
    const lv_font_t *chip_font;
    const lv_font_t *line_font;    // reset / cost line + status line
    const lv_font_t *stats_font;
    const lv_image_dsc_t *mark_dsc;
    const lv_image_dsc_t *wordmark_dsc;
};
static OcLayout L = {};

static void compute_layout(const BoardCaps &c) {
    L.scr_w = c.width;
    L.scr_h = c.height;

    if (c.height >= 460) {
        // Large — tuned for 480x480 (AMOLED-2.16).
        L.mark_x = 20; L.mark_y = 24;
        L.wordmark_y = 32;
        L.mark_dsc = &oc_mark_l;
        L.wordmark_dsc = &oc_wordmark_l;
        L.panel_x = 20; L.panel_h = 132; L.panel1_y = 96; L.panel2_y = 240;
        L.pad_x = 16;
        L.hero_top = 12;
        L.chip_top = 18; L.chip_h = 26; L.chip_px = 8;
        L.bar_top = 72; L.bar_segs = 34; L.bar_seg_w = 10; L.bar_seg_h = 20; L.bar_gap = 2;
        L.reset_top = 104;
        L.has_stats = true;
        L.stats_title_y = 386; L.stats_val_y = 410;
        L.stats_x[0] = 20; L.stats_x[1] = 150; L.stats_x[2] = 370;
        L.stats_trunc = 12;
        L.status_y = 448; L.status_sq = 10; L.status_text_x = 38;
        L.hero_font = &font_plex_48;
        L.chip_font = &font_plex_18;
        L.line_font = &font_plex_18;
        L.stats_font = &font_plex_18;
    } else if (c.height >= 300) {
        // Compact — tuned for 368x448 (AMOLED-1.8).
        L.mark_x = 20; L.mark_y = 22;
        L.wordmark_y = 30;
        L.mark_dsc = &oc_mark_m;
        L.wordmark_dsc = &oc_wordmark_m;
        L.panel_x = 20; L.panel_h = 116; L.panel1_y = 80; L.panel2_y = 206;
        L.pad_x = 14;
        L.hero_top = 10;
        L.chip_top = 14; L.chip_h = 22; L.chip_px = 6;
        L.bar_top = 60; L.bar_segs = 25; L.bar_seg_w = 10; L.bar_seg_h = 16; L.bar_gap = 2;
        L.reset_top = 92;
        L.has_stats = true;
        L.stats_title_y = 334; L.stats_val_y = 356;
        L.stats_x[0] = 20; L.stats_x[1] = 120; L.stats_x[2] = 276;
        L.stats_trunc = 9;
        L.status_y = 404; L.status_sq = 8; L.status_text_x = 34;
        L.hero_font = &font_plex_40;
        L.chip_font = &font_plex_16;
        L.line_font = &font_plex_16;
        L.stats_font = &font_plex_16;
    } else {
        // Small — tuned for 240x240 (LCD-1.54): no stats block at all.
        L.mark_x = 8; L.mark_y = 6;
        L.wordmark_y = 10;
        L.mark_dsc = &oc_mark_s;
        L.wordmark_dsc = &oc_wordmark_s;
        L.panel_x = 8; L.panel_h = 82; L.panel1_y = 34; L.panel2_y = 122;
        L.pad_x = 8;
        L.hero_top = 6;
        L.chip_top = 8; L.chip_h = 16; L.chip_px = 5;
        L.bar_top = 38; L.bar_segs = 18; L.bar_seg_w = 9; L.bar_seg_h = 10; L.bar_gap = 2;
        L.reset_top = 58;
        L.has_stats = false;
        L.status_y = 214; L.status_sq = 6; L.status_text_x = 18;
        L.hero_font = &font_plex_24;
        L.chip_font = &font_plex_12;
        L.line_font = &font_plex_12;
        L.stats_font = &font_plex_12;
    }

    // Panels span the screen minus both margins, and the wordmark is centred
    // whatever the board's width is (the generated images are 195/156/117 px).
    L.panel_w = L.scr_w - 2 * L.panel_x;
    L.wordmark_x = (L.scr_w - L.wordmark_dsc->header.w) / 2;

    // Boards that land on the large breakpoint with a narrower panel than
    // 480 px (e.g. the 410x502 AMOLED-2.06) keep the segment count and let
    // the blocks shrink instead of running off the panel.
    int16_t avail = L.panel_w - 2 * L.pad_x;
    int16_t fits = (avail - (L.bar_segs - 1) * L.bar_gap) / L.bar_segs;
    if (fits > 0 && L.bar_seg_w > fits) L.bar_seg_w = fits;
}

// ---- Widgets ----
static lv_obj_t *root;                                    // the screen container
static lv_obj_t *dim_group;                               // panels + stats: dimmed when stale
static lv_obj_t *panel[OC_PANELS];
static lv_obj_t *hero[OC_PANELS];
static lv_obj_t *chip[OC_PANELS];
static lv_obj_t *seg[OC_PANELS][OC_SEG_MAX];
static lv_obj_t *reset_lbl[OC_PANELS];
static lv_obj_t *stats_title[3];
static lv_obj_t *stats_val[3];
static lv_obj_t *status_sq;                               // blinking "session active" square
static lv_obj_t *status_lbl;

// ---- State ----
static OcData   cur;                 // last payload, copied by value
static bool     have_data = false;   // a valid payload arrived since boot
static uint32_t data_ms = 0;         // millis() of that payload
static bool     ble_on = false;
static bool     dimmed = false;      // current opacity of dim_group
static bool     bar_vis[OC_PANELS] = { false, false };
static bool     sq_shown = false;    // square currently visible
static bool     blink_on = true;
static uint32_t blink_ms = 0;
static char     status_text[48] = "";
// Both start out "unset" (black is never a status colour, -1 is no x) so the
// first draw always pushes them; after that only real changes reach LVGL.
static lv_color_t status_color;
static int16_t  status_x = -1;

static void draw_status(uint32_t now);
static void apply_dim(bool stale);
static void redraw(void);

// ---- Formatting (mirrors the prototype's helpers) ----

// "42m" / "2h 14m" / "6d 13h"; an unknown countdown shows the ellipsis.
static const char *fmt_mins(int mins) {
    static char buf[12];
    if (mins < 0) return OC_ELLIPSIS;
    if (mins >= 1440)      snprintf(buf, sizeof(buf), "%dd %dh", mins / 1440, (mins % 1440) / 60);
    else if (mins >= 60)   snprintf(buf, sizeof(buf), "%dh %dm", mins / 60, mins % 60);
    else                   snprintf(buf, sizeof(buf), "%dm", mins);
    return buf;
}

// "35s" / "21m" / "3h 4m" — the "… ago" suffix of the status line.
static const char *fmt_age(long secs) {
    static char buf[12];
    if (secs < 0) secs = 0;
    if (secs < 60)        snprintf(buf, sizeof(buf), "%lds", secs);
    else if (secs < 3600) snprintf(buf, sizeof(buf), "%ldm", secs / 60);
    else                  snprintf(buf, sizeof(buf), "%ldh %ldm", secs / 3600, (secs % 3600) / 60);
    return buf;
}

// Tokens arrive in thousands: 812 -> "812k", 3200 -> "3.2M", 106969 -> "107.0M".
static const char *fmt_tokens(long thousands) {
    static char buf[12];
    if (thousands < 0) thousands = 0;
    if (thousands < 1000)        snprintf(buf, sizeof(buf), "%ldk", thousands);
    else if (thousands < 1000000) snprintf(buf, sizeof(buf), "%.1fM", thousands / 1000.0f);
    else                          snprintf(buf, sizeof(buf), "%.1fB", thousands / 1000000.0f);
    return buf;
}

// "ds-v4.1-flash" -> "ds-v4.1-fl…" so the columns never collide (Annex A).
static void fmt_model(char *out, size_t len) {
    if ((int)strlen(cur.m) > L.stats_trunc)
        snprintf(out, len, "%.*s" OC_ELLIPSIS, L.stats_trunc, cur.m);
    else
        snprintf(out, len, "%s", cur.m);
}

static bool is_stale(uint32_t now) {
    return have_data && (now - data_ms) > OC_FRESH_MS;
}

// ---- Builders ----

// Transparent, borderless, click-through group. EVENT_BUBBLE on every widget
// so a tap anywhere reaches the screen root, where ui.cpp listens.
static lv_obj_t *make_group(lv_obj_t *parent) {
    lv_obj_t *g = lv_obj_create(parent);
    lv_obj_set_size(g, L.scr_w, L.scr_h);
    lv_obj_set_pos(g, 0, 0);
    lv_obj_set_style_bg_opa(g, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(g, 0, 0);
    lv_obj_set_style_pad_all(g, 0, 0);
    lv_obj_clear_flag(g, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(g, LV_OBJ_FLAG_EVENT_BUBBLE);
    return g;
}

// Thin square-cornered outline; children are positioned by hand.
static lv_obj_t *make_panel(lv_obj_t *parent, int16_t y) {
    lv_obj_t *p = lv_obj_create(parent);
    lv_obj_set_pos(p, L.panel_x, y);
    lv_obj_set_size(p, L.panel_w, L.panel_h);
    lv_obj_set_style_bg_opa(p, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_color(p, OC_BORDER, 0);
    lv_obj_set_style_border_width(p, 1, 0);
    lv_obj_set_style_radius(p, 0, 0);
    lv_obj_set_style_pad_all(p, 0, 0);
    lv_obj_clear_flag(p, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(p, LV_OBJ_FLAG_EVENT_BUBBLE);
    return p;
}

static lv_obj_t *make_label(lv_obj_t *parent, int16_t x, int16_t y,
                            const lv_font_t *font, lv_color_t color) {
    lv_obj_t *l = lv_label_create(parent);
    lv_obj_set_pos(l, x, y);
    lv_obj_set_style_text_font(l, font, 0);
    lv_obj_set_style_text_color(l, color, 0);
    lv_obj_set_style_pad_all(l, 0, 0);
    // One line, like the prototype's white-space: nowrap.
    lv_label_set_long_mode(l, LV_LABEL_LONG_MODE_CLIP);
    lv_obj_add_flag(l, LV_OBJ_FLAG_EVENT_BUBBLE);
    return l;
}

// Terminal-style chip: flat fill, horizontal padding, fixed height, pinned to
// the panel's right padding.
static lv_obj_t *make_chip(lv_obj_t *parent, int16_t y) {
    lv_obj_t *c = make_label(parent, 0, y, L.chip_font, OC_PRIMARY);
    int16_t text_h = lv_font_get_line_height(L.chip_font);
    lv_obj_set_style_bg_color(c, OC_ELEMENT, 0);
    lv_obj_set_style_bg_opa(c, LV_OPA_COVER, 0);
    lv_obj_set_style_radius(c, 0, 0);
    lv_obj_set_style_pad_left(c, L.chip_px, 0);
    lv_obj_set_style_pad_right(c, L.chip_px, 0);
    lv_obj_set_style_pad_top(c, (L.chip_h - text_h) / 2, 0);
    lv_obj_set_style_pad_bottom(c, L.chip_h - text_h - (L.chip_h - text_h) / 2, 0);
    lv_obj_set_height(c, L.chip_h);
    // Width follows the text, so the right alignment is recomputed by LVGL
    // whenever the label's text changes.
    lv_obj_align(c, LV_ALIGN_TOP_RIGHT, -L.pad_x, y);
    return c;
}

static lv_obj_t *make_seg(lv_obj_t *parent, int16_t x, int16_t y) {
    lv_obj_t *s = lv_obj_create(parent);
    lv_obj_set_pos(s, x, y);
    lv_obj_set_size(s, L.bar_seg_w, L.bar_seg_h);
    lv_obj_set_style_bg_color(s, OC_ELEMENT, 0);
    lv_obj_set_style_bg_opa(s, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(s, 0, 0);
    lv_obj_set_style_radius(s, 0, 0);
    lv_obj_set_style_pad_all(s, 0, 0);
    lv_obj_clear_flag(s, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s, LV_OBJ_FLAG_EVENT_BUBBLE);
    return s;
}

static void build_panel(int i, int16_t y) {
    panel[i] = make_panel(dim_group, y);
    hero[i] = make_label(panel[i], L.pad_x, L.hero_top, L.hero_font, OC_TEXT);
    chip[i] = make_chip(panel[i], L.chip_top);
    for (int k = 0; k < L.bar_segs; k++)
        seg[i][k] = make_seg(panel[i], L.pad_x + k * (L.bar_seg_w + L.bar_gap), L.bar_top);
    reset_lbl[i] = make_label(panel[i], L.pad_x, L.reset_top, L.line_font, OC_MUTED);
}

void oc_usage_init(lv_obj_t *parent) {
    compute_layout(board_caps());

    root = make_group(parent);
    // The mark and the wordmark stay at full opacity even when the numbers
    // below are dimmed. The battery widget is ui.cpp's and stays on top.
    lv_obj_t *mark = lv_image_create(root);
    lv_image_set_src(mark, L.mark_dsc);
    lv_obj_set_pos(mark, L.mark_x, L.mark_y);
    lv_obj_add_flag(mark, LV_OBJ_FLAG_EVENT_BUBBLE);

    lv_obj_t *wordmark = lv_image_create(root);
    lv_image_set_src(wordmark, L.wordmark_dsc);
    lv_obj_set_pos(wordmark, L.wordmark_x, L.wordmark_y);
    lv_obj_add_flag(wordmark, LV_OBJ_FLAG_EVENT_BUBBLE);

    dim_group = make_group(root);
    build_panel(0, L.panel1_y);
    build_panel(1, L.panel2_y);

    if (L.has_stats) {
        for (int i = 0; i < 3; i++) {
            stats_title[i] = make_label(dim_group, L.stats_x[i], L.stats_title_y, L.stats_font, OC_TEXT);
            stats_val[i] = make_label(dim_group, L.stats_x[i], L.stats_val_y, L.stats_font, OC_MUTED);
        }
    }

    // Status line (outside dim_group). The square sits on the screen margin
    // and is centred on the text line; see draw_status() for the text x.
    status_sq = lv_obj_create(root);
    lv_obj_set_pos(status_sq, L.panel_x,
                   L.status_y + (lv_font_get_line_height(L.line_font) - L.status_sq) / 2);
    lv_obj_set_size(status_sq, L.status_sq, L.status_sq);
    lv_obj_set_style_bg_color(status_sq, OC_SUCCESS, 0);
    lv_obj_set_style_bg_opa(status_sq, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(status_sq, 0, 0);
    lv_obj_set_style_radius(status_sq, 0, 0);
    lv_obj_set_style_pad_all(status_sq, 0, 0);
    lv_obj_clear_flag(status_sq, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(status_sq, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_add_flag(status_sq, LV_OBJ_FLAG_HIDDEN);

    status_lbl = make_label(root, L.panel_x, L.status_y, L.line_font, OC_MUTED);
    lv_label_set_text(status_lbl, "");

    // Neutral state, so the screen is never blank if it is shown before the
    // first payload (ui.cpp keeps the OC screens out of the cycle until then).
    memset(&cur, 0, sizeof(cur));
    strlcpy(cur.src, "api", sizeof(cur.src));
    cur.r5 = cur.rw = -1;
    redraw();

    lv_obj_add_flag(root, LV_OBJ_FLAG_HIDDEN);
}

// ---- Drawing ----

static void set_bar_visible(int i, bool on) {
    if (bar_vis[i] == on) return;
    bar_vis[i] = on;
    for (int k = 0; k < L.bar_segs; k++) {
        if (on) lv_obj_clear_flag(seg[i][k], LV_OBJ_FLAG_HIDDEN);
        else     lv_obj_add_flag(seg[i][k], LV_OBJ_FLAG_HIDDEN);
    }
}

static void draw_bar(int i, int pct) {
    bool hot = (pct >= 85 || cur.limited);
    lv_color_t fill = hot ? OC_ERROR : OC_PRIMARY;
    int filled = (pct * L.bar_segs + 50) / 100;   // round(pct/100 * segs)
    if (filled < 0) filled = 0;
    if (filled > L.bar_segs) filled = L.bar_segs;
    for (int k = 0; k < L.bar_segs; k++)
        lv_obj_set_style_bg_color(seg[i][k], k < filled ? fill : OC_ELEMENT, 0);
}

static void draw_panels(bool solo) {
    const int pct[OC_PANELS] = { cur.p5, cur.pw };
    const int rst[OC_PANELS] = { cur.r5, cur.rw };
    const long tok[OC_PANELS] = { cur.tk, cur.t7 };
    const float money[OC_PANELS] = { cur.cd, cur.c7 };

    for (int i = 0; i < OC_PANELS; i++) {
        if (solo) lv_label_set_text(hero[i], fmt_tokens(tok[i]));
        else       lv_label_set_text_fmt(hero[i], "%d%%", pct[i]);

        // Consumption-only mode swaps the window chip for what the hero shows.
        char cbuf[24];
        if (solo) {
            snprintf(cbuf, sizeof(cbuf), "%s", i == 0 ? "today" : "7 days");
        } else if (cur.limited && pct[i] >= 100) {
            snprintf(cbuf, sizeof(cbuf), "limit");
        } else if (strcmp(cur.src, "est") == 0) {
            snprintf(cbuf, sizeof(cbuf), "%s " OC_MIDDOT " est.", i == 0 ? "5h" : "week");
        } else {
            snprintf(cbuf, sizeof(cbuf), "%s", i == 0 ? "5h" : "week");
        }
        lv_label_set_text(chip[i], cbuf);
        lv_obj_set_style_text_color(chip[i],
                                    (pct[i] >= 85 || cur.limited) ? OC_ERROR : OC_PRIMARY, 0);

        set_bar_visible(i, !solo);
        if (!solo) draw_bar(i, pct[i]);

        // Money goes through snprintf: lv_label_set_text_fmt() runs LVGL's own
        // printf, which has no float support (LV_USE_FLOAT is off).
        char mbuf[24];
        if (solo) {
            snprintf(mbuf, sizeof(mbuf), "$%.2f spent", money[i]);
            lv_label_set_text(reset_lbl[i], mbuf);
        } else if (i == 0 && cur.r5 == -1) {
            lv_label_set_text(reset_lbl[i], "No active window");
        } else {
            lv_label_set_text_fmt(reset_lbl[i], "Resets in %s", fmt_mins(rst[i]));
        }
    }
}

static void draw_stats(bool solo) {
    if (!L.has_stats) return;

    char model[20];
    char val[24];
    fmt_model(model, sizeof(model));

    lv_label_set_text(stats_title[0], "7d tokens");
    lv_label_set_text(stats_title[1], "top model");
    lv_label_set_text(stats_title[2], solo ? "7d cost" : "month");

    lv_label_set_text(stats_val[0], fmt_tokens(cur.t7));
    snprintf(val, sizeof(val), "%s %d%%", model, cur.ms);
    lv_label_set_text(stats_val[1], val);
    if (solo) {
        snprintf(val, sizeof(val), "$%.2f", cur.c7);
    } else {
        // Month percentage + whole days left in the billing period.
        snprintf(val, sizeof(val), "%d%% " OC_MIDDOT " %dd", cur.pm, (cur.rm + 720) / 1440);
    }
    lv_label_set_text(stats_val[2], val);
}

// SPEC.md §7. The line lives outside dim_group: it is how the user learns the
// numbers above are stale or the link is down. oc_usage_tick() runs this every
// loop, so only what actually changed is pushed to LVGL.
static void draw_status(uint32_t now) {
    char buf[48];
    const char *text;
    lv_color_t color;
    bool dot;

    if (!ble_on) {
        text = OC_CIRCLE " bluetooth disconnected";
        color = OC_ERROR;
        dot = false;
    } else if (is_stale(now)) {
        snprintf(buf, sizeof(buf), OC_CIRCLE " stale " OC_MIDDOT " updated %s ago",
                 fmt_age((long)((now - data_ms) / 1000)));
        text = buf;
        color = OC_ERROR;
        dot = false;
    } else if (cur.a >= 1) {
        if (cur.ag[0]) snprintf(buf, sizeof(buf), "%s " OC_MIDDOT " working", cur.ag);
        else           snprintf(buf, sizeof(buf), "working");
        text = buf;
        color = OC_TEXT;
        dot = true;
    } else {
        long age = cur.la + (have_data ? (long)((now - data_ms) / 1000) : 0);
        snprintf(buf, sizeof(buf), "idle " OC_MIDDOT " last activity %s ago", fmt_age(age));
        text = buf;
        color = OC_MUTED;
        dot = false;
    }

    if (strcmp(text, status_text) != 0) {
        lv_label_set_text(status_lbl, text);
        strlcpy(status_text, text, sizeof(status_text));
    }
    if (!lv_color_eq(color, status_color)) {
        status_color = color;
        lv_obj_set_style_text_color(status_lbl, color, 0);
    }
    // The active state indents the text to clear the blinking square; the
    // other three states start on the screen margin (Annex A).
    int16_t x = dot ? L.status_text_x : L.panel_x;
    if (x != status_x) {
        status_x = x;
        lv_obj_set_pos(status_lbl, x, L.status_y);
    }

    if (dot != sq_shown) {
        sq_shown = dot;
        if (dot) {
            blink_on = true;
            blink_ms = now;
            lv_obj_set_style_bg_opa(status_sq, LV_OPA_COVER, 0);
            lv_obj_clear_flag(status_sq, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(status_sq, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

static void apply_dim(bool stale) {
    bool dim = stale || !ble_on;
    if (dim == dimmed) return;
    dimmed = dim;
    // opa is inherited, so the panels and the stats fade as one block while
    // the header and the status line keep full opacity.
    lv_obj_set_style_opa(dim_group, dim ? LV_OPA_40 : LV_OPA_COVER, 0);
}

static void redraw(void) {
    if (!root) return;
    bool solo = strcmp(cur.src, "none") == 0;
    uint32_t now = millis();
    draw_panels(solo);
    draw_stats(solo);
    draw_status(now);
    apply_dim(is_stale(now));
}

// ======== Public API ========

void oc_usage_show(void) {
    if (!root) return;
    lv_obj_clear_flag(root, LV_OBJ_FLAG_HIDDEN);
    redraw();               // the countdown and the "ago" suffix moved while hidden
}

void oc_usage_hide(void) {
    if (!root) return;
    lv_obj_add_flag(root, LV_OBJ_FLAG_HIDDEN);
}

lv_obj_t *oc_usage_get_root(void) {
    return root;
}

void oc_usage_update(const OcData *d) {
    if (!d) return;
    cur = *d;
    data_ms = millis();
    if (d->valid) have_data = true;
    redraw();
}

void oc_usage_set_ble(bool connected) {
    ble_on = connected;
    redraw();
}

void oc_usage_tick(void) {
    if (!root) return;
    uint32_t now = millis();

    // Both the stale switch and the "… ago" counters are time-based, so they
    // keep running between the ~60 s payloads.
    apply_dim(is_stale(now));
    draw_status(now);

    if (sq_shown && now - blink_ms >= OC_BLINK_MS) {
        blink_ms = now;
        blink_on = !blink_on;
        lv_obj_set_style_bg_opa(status_sq, blink_on ? LV_OPA_COVER : LV_OPA_30, 0);
    }
}

bool oc_has_data(void) {
    return have_data;
}
