#!/usr/bin/env node
/**
 * Generates firmware/src/oc_logo.h — the OpenCode mark and wordmark as
 * LVGL image descriptors.
 *
 * The art is the two pixel grids below, taken from
 * design/opencode-screen/IMPL.md (WP1). Each character is one cell of a
 * low-resolution logo grid; a cell expands to a `cell`-pixel square, so the
 * mark and the wordmark come out pixel-crisp at every size instead of being
 * resampled. No SVG tooling involved.
 *
 * Output: RGB565 little-endian byte arrays plus a `static const
 * lv_image_dsc_t` per size, on an opaque black background (the screens the
 * logo appears on are black, so no alpha channel is needed).
 *
 * Usage: node gen_oc_logo.js [--out FILE]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const opt = (k, def) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : def; };
const OUT_FILE = path.resolve(opt('--out', path.join(__dirname, '..', 'firmware', 'src', 'oc_logo.h')));

// IMPL.md §WP1: `O` #F1ECEC, `i` #4B4646, `.` black.
const MARK_GRID = [
  'OOOO',
  'O..O',
  'OiiO',
  'OiiO',
  'OOOO',
];
const MARK_COLORS = { O: '#F1ECEC', i: '#4B4646', '.': '#000000' };

// IMPL.md §WP1: `B` #B7B1B1, `C` #F1ECEC, `A` #4B4646, `.` black.
const WORDMARK_GRID = [
  '.................................C.....',
  'BBBB.BBBB.BBBB.BBB..CCCC.CCCC.CCCC.CCCC',
  'B..B.B..B.B..B.B..B.C....C..C.C..C.C..C',
  'BAAB.BAAB.BBBB.BAAB.CAAA.CAAC.CAAC.CCCC',
  'BAAB.BAAB.BAAA.BAAB.CAAA.CAAC.CAAC.CAAA',
  'BBBB.BBBB.BBBB.BAAB.CCCC.CCCC.CCCC.CCCC',
  '.....B.................................',
];
const WORDMARK_COLORS = { B: '#B7B1B1', C: '#F1ECEC', A: '#4B4646', '.': '#000000' };

// Cells per pixel-square, per size. 10/8/4 for the mark, 5/4/3 for the
// wordmark — IMPL.md fixes the resulting pixel dimensions (40x50 / 32x40 /
// 16x20 and 195x35 / 156x28 / 117x21).
const SIZES = [
  { name: 'mark',     cell: { l: 10, m: 8,  s: 4 } },
  { name: 'wordmark', cell: { l: 5,  m: 4,  s: 3 } },
];

const BYTES_PER_LINE = 16;

function hexToRgb565(hex) {
  const n = parseInt(hex.replace('#', ''), 16);
  const r = (n >> 16) & 0xFF, g = (n >> 8) & 0xFF, b = n & 0xFF;
  return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

function checkGrid(grid, colors, what) {
  const w = grid[0].length;
  grid.forEach((row, y) => {
    if (row.length !== w) throw new Error(`${what}: row ${y} is ${row.length} cells, expected ${w}`);
    for (const ch of row)
      if (!(ch in colors)) throw new Error(`${what}: row ${y} has unknown cell '${ch}'`);
  });
  return w;
}

// Cell grid → flat RGB565 little-endian bytes at `cell` px per cell.
function render(grid, colors, cell) {
  const cellsW = grid[0].length, cellsH = grid.length;
  const w = cellsW * cell, h = cellsH * cell;
  const bytes = [];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const px = hexToRgb565(colors[grid[(y / cell) | 0][(x / cell) | 0]]);
      bytes.push(px & 0xFF, (px >> 8) & 0xFF);   // little-endian
    }
  }
  return { w, h, bytes };
}

function main() {
  let out = '';
  out += '// ============================================================\n';
  out += '// OpenCode logo — generated by tools/gen_oc_logo.js.\n';
  out += '// Source: the OpenCode logo, github.com/anomalyco/opencode (MIT).\n';
  out += '// The mark and wordmark are the pixel grids in\n';
  out += '// design/opencode-screen/IMPL.md, each cell expanded to a square\n';
  out += '// block — no resampling, so every size stays crisp.\n';
  out += '// Do not edit by hand — re-run the generator to refresh.\n';
  out += '// ============================================================\n';
  out += '#pragma once\n#include <stdint.h>\n';
  out += '#include "lvgl.h"\n\n';

  for (const { name, cell } of SIZES) {
    const grid = name === 'mark' ? MARK_GRID : WORDMARK_GRID;
    const colors = name === 'mark' ? MARK_COLORS : WORDMARK_COLORS;
    const cellsW = checkGrid(grid, colors, name);

    for (const s of ['l', 'm', 's']) {
      const px = cell[s];
      const sym = `oc_${name}_${s}`;
      const { w, h, bytes } = render(grid, colors, px);

      out += `#define ${sym.toUpperCase()}_W ${w}   /* ${cellsW} cells x ${px} px */\n`;
      out += `#define ${sym.toUpperCase()}_H ${h}   /* ${grid.length} cells x ${px} px */\n`;
      out += `static const uint8_t ${sym}_data[${bytes.length}] = {\n`;
      for (let i = 0; i < bytes.length; i += BYTES_PER_LINE) {
        const row = bytes.slice(i, i + BYTES_PER_LINE)
          .map(b => `0x${b.toString(16).toUpperCase().padStart(2, '0')}`).join(', ');
        out += `    ${row},\n`;
      }
      out += '};\n\n';
      out += `static const lv_image_dsc_t ${sym} = {\n`;
      out += '    .header = {\n';
      out += '        .magic = LV_IMAGE_HEADER_MAGIC,\n';
      out += '        .cf = LV_COLOR_FORMAT_RGB565,\n';
      out += '        .flags = 0,\n';
      out += `        .w = ${w},\n`;
      out += `        .h = ${h},\n`;
      out += `        .stride = ${w} * 2,\n`;
      out += '        .reserved_2 = 0,\n';
      out += '    },\n';
      out += `    .data_size = sizeof(${sym}_data),\n`;
      out += `    .data = ${sym}_data,\n`;
      out += '    .reserved = NULL,\n';
      out += '    .reserved_2 = NULL,\n';
      out += '};\n\n';
      console.log(`  ${sym.padEnd(14)} ${String(w).padStart(3)}x${String(h).padEnd(3)} ` +
        `${(bytes.length / 1024).toFixed(1)} KB (cell ${px}px)`);
    }
  }

  fs.writeFileSync(OUT_FILE, out);
  console.log(`\nWrote ${OUT_FILE} (${(out.length / 1024).toFixed(0)} KB source)`);
}

main();
